# vim:ft=ansible:
---

- name: copy files
  copy: src="{{ item }}" dest="/var/tmp/" mode="0644"
  register: file
  with_fileglob:
    - "../files/*{{ role_name_scaleio }}*"
  when: ansible_distribution == "RedHat"

- name: Are rpm files in correct location?
  debug: msg="RPM files are not located in the ansible-scaleio/files area.  Please read readme in that folder for location to download from"
  when: file.results is not defined

- name: install package
  yum: name="{{ file.results[0].dest }}" state="present"
  environment:
    MDM_IP: "{{ scaleio_mdm_ips }}"
    MDM_ROLE_IS_MANAGER: "{{ node_is_manager }}"
    GATEWAY_ADMIN_PASSWORD: "{{ scaleio.password }}"
  when: ansible_distribution == "RedHat"

- name: cleanup tmp folder
  command: rm -rf "/var/tmp/{{item}}"
  with_fileglob:
    - "../files/*{{ role_name_scaleio }}*"
  when: ansible_distribution == "RedHat"

