- set_fact: role_name="mdm
- set_fact: node_is_manager=0

- debug: msg={{ role_name }}

- include: ../../install_scaleio.yml

#- name: login with new password
#  command: scli --login --username admin --password "{{ scaleio.password }}"
#  run_once: true
#  delegate_to: "{{ scaleio.mdm1_name }}"
#
#- name: add tie breaker 1
#  command: scli --add_standby_mdm --new_mdm_ip "{{ scaleio.tb1_ip }}" --mdm_role tb --new_mdm_name "{{ scaleio.tb1_name }}"
#  run_once: true
#  delegate_to: "{{ scaleio.mdm1_name }}"
#  register: add_tb
#  changed_when: "'single mode' not in add_tb.stderr"
#  ignore_errors: true

- name: login with new password
  command: scli --login --username admin --password "{{ scaleio.password }}"
  run_once: true
  delegate_to: "{{ scaleio.mdm1_name }}"

- name: add primary tie breaker
  command: scli --add_standby_mdm --new_mdm_ip "{{ scaleio.tb1_ip }}"  --mdm_role tb
  run_once: true
  delegate_to: "{{ scaleio.mdm1_name }}"
  register: add_tb
  changed_when: "'single mode' not in add_tb.stderr"
  ignore_errors: true

- name: add secondary tie breaker
  command: scli --add_standby_mdm --new_mdm_ip "{{ scaleio.tb2_ip }}"  --mdm_role tb
  run_once: true
  delegate_to: "{{ scaleio.mdm1_name }}"
  register: add_tb
  changed_when: ("'single mode' not in add_tb.stderr") and (scaleio.tb2_ip is defined)
  ignore_errors: true
  when: scaleio.tb2_ip is defined

- name: switch to cluster three node
  command: scli --switch_cluster_mode --cluster_mode "{{ scaleio.cluster_mode }}" --add_slave_mdm_ip  "{{ scaleio.mdm2_ip }}" --add_tb_ip "{{ scaleio.tb1_ip }}"
  run_once: true
  delegate_to: "{{ scaleio.mdm1_name }}"
  when: ("'single mode' not in add_tb.stderr") and  ( scaleio.cluster_mode  == "3_node")
  ignore_errors: true

- name: switch to cluster five node
  command: scli --switch_cluster_mode --cluster_mode "{{ scaleio.cluster_mode }}" --add_slave_mdm_ip  "{{ scaleio.mdm2_ip }}","{{ scaleio.mdm3_ip }}" --add_tb_ip "{{ scaleio.tb1_ip }}","{{ scaleio.tb2_ip }}"
  run_once: true
  delegate_to: "{{ scaleio.mdm1_name }}"
  when: ("'single mode' not in add_tb.stderr") and ( scaleio.cluster_mode == "5_node")
  ignore_errors: true

- name: create the protection domain
  command: scli --add_protection_domain --mdm_ip "{{ scaleio.mdm1_ip }}" --protection_domain_name {{ scaleio.protection_domain }}
  run_once: true
  delegate_to: "{{ scaleio.mdm1_name }}"
  register: add_pd
  changed_when: "'already exists' not in add_pd.stderr"
  ignore_errors: true

- name: add storage pool
  command: scli --mdm_ip {{ scaleio.mdm_ips }} --add_storage_pool --protection_domain_name {{ scaleio.protection_domain }} --storage_pool_name {{ scaleio.storage_pool }}
  run_once: true
  register: storage_pool_add
  delegate_to: "{{ scaleio.mdm1_name }}"
  changed_when: (storage_pool_add.rc == 7) or (storage_pool_add.rc == 0)
  ignore_errors: yes
